# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# I find using a list of criteria easier to read/write than a long series of infix operators. The
# scoping also seems to be easier since the commas separate entire sections.
- ignore: {name: Use &&} 
- ignore: {name: Use ||}
- ignore: {name: Use ++}

# Lambda case is less clear than `case x of`. For newbies to haskell, I think the latter is better.
- ignore: {name: Use lambda-case}
